version: '3'
services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strong-password
    restart: always
    volumes:
      - mongodb-data:/data/db
  
  crawler:
    container_name: crawler
    image: python:3.6
    environment:
      - ROOT_URL=https://url.com/
      - ALLOWS_FOREIGN_URLS=false
    ports:
      - "5000:5000"
    volumes:
      - .:/simple-web-crawling
    restart: always
    command: >
      bash -c "cd /simple-web-crawling && 
      pip install --upgrade pip && 
      pip install -r ./requirements.txt && 
      python run.py"

volumes:
  mongodb-data: